version: "3.9"

services:
  gateway-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: gateway
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s
    labels:
      - "coolify.exposed_port=8000"

  account-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: account-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s

  post-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: post-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s

  # Node JS Worker Instance
  node-worker-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: worker-service
        APP_PATH: apps/worker-service/node-worker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s

  # Go Worker Instance
  go-worker-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: go-runner
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f go-worker-bin || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s

  platform-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: node-runner
      args:
        SERVICE_NAME: platform-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/health"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s
