import { ThemeProvider } from "@mui/material/styles";
import theme from "@/themes/theme";
import CssBaseline from "@mui/material/CssBaseline";
import { ContextProvider } from "./GlobalContext";
import { Metadata } from "next";
import { GlobalManager } from "./GlobalManager";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';


export const metadata: Metadata = {
  title: "Funstakes",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "JavaScript"],
  manifest: "/manifest.json",
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  icons: {
    icon: "/favicon.ico",
    other: {
      rel: "apple-touch-icon",
      url: "logo.png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@200,300,400,500,700&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <AppRouterCacheProvider>
          <ContextProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <GlobalManager>{children}</GlobalManager>
            </ThemeProvider>
          </ContextProvider>
        </AppRouterCacheProvider>
        <noscript>You need to enable JavaScript to run this app!</noscript>
      </body>
    </html>
  );
}
